// Regenerates lib/src/registry/implementation_ids.g.dart from the shared
// implementationID → type name map in .docs/implementation_id_to_type.json.
//
//   dart run packages/matillion_core/tool/gen_registry.dart
//
// The map is embedded as Dart so it works on the web without asset loading.
// A unit test fails when the generated file and the JSON drift apart.

import 'dart:convert';
import 'dart:io';

void main() {
  final pkg = File.fromUri(Platform.script).parent.parent;
  final source = File('${pkg.parent.parent.path}/.docs/implementation_id_to_type.json');
  final map = (jsonDecode(source.readAsStringSync()) as Map<String, dynamic>).cast<String, String>();

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_registry.dart from .docs/implementation_id_to_type.json.')
    ..writeln('// Do not edit by hand.')
    ..writeln()
    ..writeln('/// implementationID → component type name, shared by all Matillion ETL variants.')
    ..writeln('const Map<int, String> sharedImplementationIds = {');
  map.forEach((id, name) => out.writeln("  $id: '${name.replaceAll("'", r"\'")}',"));
  out.writeln('};');

  File('${pkg.path}/lib/src/registry/implementation_ids.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('Wrote ${map.length} implementation IDs.');
}
